Repository swiftwasm/swift, pull requests merged in 2020-10, with the labels that each got.

#1886 Disable assertions for both target and host toolchain in 5.3 branch
  utils/build-presets.ini
  utils/webassembly/build-foundation.sh
  utils/webassembly/build-toolchain.sh
  utils/webassembly/build-xctest.sh
  utils/webassembly/ci.sh
Labels: release

#1799 Build 5.3 branch with Xcode GM on GitHub Actions
  .github/workflows/main.yml
Labels: continuous integration, release

#1914 State CPU arch in names of distribution tarballs
  .github/workflows/main.yml
  utils/webassembly/build-toolchain.sh
  utils/webassembly/distribute-latest-toolchain.sh
Labels: continuous integration

#1910 Re-enable all Wasm stdlib tests on Linux for 5.3
  test/lit.cfg
  utils/webassembly/ci.sh
  utils/webassembly/macos/install-dependencies.sh
Labels: continuous integration, release

#1921 Set compiler vendor name as SwiftWasm
  utils/build_swift/build_swift/driver_arguments.py
  utils/swift_build_support/swift_build_support/products/llvm.py
  utils/swift_build_support/swift_build_support/products/swift.py
  utils/webassembly/build-presets.ini
Labels: continuous integration

#1919 State CPU arch in names of 5.3 distribution tarballs
  .github/workflows/main.yml
  utils/webassembly/build-toolchain.sh
  utils/webassembly/distribute-latest-toolchain.sh
Labels: continuous integration, release

#1940 Check if Python 2 is installed before uninstalling
  utils/update_checkout/update-checkout-config.json
  utils/webassembly/macos/install-dependencies.sh
Labels: bug

#1970 Add missing packages to linux/install-dependencies.sh
  utils/webassembly/linux/install-dependencies.sh
Labels: continuous integration

#1949 Resolve conflicts and use forked SourceKit-LSP in 5.3 branch
  .github/workflows/main.yml
  utils/update_checkout/update-checkout-config.json
  utils/webassembly/linux/install-dependencies.sh
Labels: :arrow_heading_down: Upstream Tracking, continuous integration, release

#1986 Resolve conflicts in the 5.3 branch
  utils/build-script-impl
  utils/update_checkout/update-checkout-config.json
Labels: :arrow_heading_down: Upstream Tracking, release

#1684 Fix local test runs by passing real test dir path in 5.3
  utils/webassembly/build-toolchain.sh
  utils/webassembly/ci.sh
Labels: continuous integration, release

#1554 Fix local test runs by passing real test dir path
  utils/webassembly/build-toolchain.sh
  utils/webassembly/ci.sh
Labels: bug, continuous integration

#2033 Use underscore for CPU arch in dist names
  .github/workflows/main.yml
  utils/webassembly/build-toolchain.sh
  utils/webassembly/distribute-latest-toolchain.sh
Labels: bug, continuous integration

#2041 Cherry-pick packaging changes for the 5.3 branch
  .github/workflows/main.yml
  .github/workflows/nightly-distribution.yml
  utils/webassembly/build-toolchain.sh
  utils/webassembly/distribute-latest-toolchain.sh
Labels: continuous integration, release

#2056 Re-enable Xcode check as 12.2 Beta 3 is available
  .github/workflows/main.yml
Labels: continuous integration

#2070 Use macOS 10.15 on GitHub Actions
  .github/workflows/main.yml
Labels: continuous integration

#2127 Use WASI SDK 0.2.2-swiftwasm to fix setjmp headers in 5.3 branch
  utils/webassembly/install-wasi-sdk.sh
  utils/webassembly/linux/install-dependencies.sh
  utils/webassembly/macos/install-dependencies.sh
Labels: continuous integration, release

#2125 Use SwiftWasm TSC fork to enable .wasm binary ext
  utils/update_checkout/update-checkout-config.json
Labels: continuous integration, release
