Repository swiftwasm/swift, pull requests merged in 2020-09, with the labels that each got.

#1673 Fix latest run check in toolchain upload script
  utils/webassembly/distribute-latest-toolchain.sh
Labels: bug, continuous integration

#1683 Prioritize SDK paths in CMake find_ functions in 5.3 branch
  utils/build-script-impl
Labels: bug, continuous integration, release

#1798 Build with Xcode GM on GitHub Actions
  .github/workflows/main.yml
Labels: continuous integration

#1634 [WASM] Update assertion condition for keypath projector
  lib/SILOptimizer/Utils/KeyPathProjector.cpp
Labels: bug

#1810 Resolve conflicts with upstream branch renaming
  include/swift/AST/ASTScope.h
  include/swift/AST/NameLookup.h
  lib/AST/ASTScope.cpp
  lib/AST/ASTScopeCreation.cpp
  lib/AST/ASTScopeLookup.cpp
  lib/AST/ASTScopePrinting.cpp
  lib/AST/ASTScopeSourceRange.cpp
  test/ModuleInterface/stored-properties.swift
  test/NameLookup/scope_map_top_level.swift
  utils/update_checkout/update-checkout-config.json
Labels: :arrow_heading_down: Upstream Tracking

#1816 Build 5.3 branch for Ubuntu 20.04 on CI
  .github/workflows/main.yml
  utils/webassembly/build-toolchain.sh
  utils/webassembly/distribute-latest-toolchain.sh
  utils/webassembly/linux/install-dependencies.sh
Labels: continuous integration, release

#1811 Build for Ubuntu 20.04 on CI
  .github/workflows/main.yml
  utils/webassembly/build-toolchain.sh
  utils/webassembly/distribute-latest-toolchain.sh
  utils/webassembly/linux/install-dependencies.sh
Labels: continuous integration

#1834 Make hello.wasm naming consistent in 5.3 branch
  .github/workflows/main.yml
Labels: continuous integration, release

#1835 Make hello.wasm naming consistent on CI
  .github/workflows/main.yml
Labels: continuous integration

#1851 Ship IndexStore and SourceKit-LSP in 5.3 snapshots
  utils/build-presets.ini
Labels: continuous integration, release

#1848 Fix broken test script
  .github/workflows/main.yml
  test/lit.cfg
  utils/webassembly/ci.sh
Labels: continuous integration
