Repository swiftwasm/swift, pull requests merged in 2022-04, with the labels that each got.

#4396 Prepare SwiftWasm 5.6.0 release
  .github/workflows/manual-distribution.yml
  utils/webassembly/build-presets.ini
  utils/webassembly/build-toolchain.sh
Labels: release

#4407 Merge main 2022-04-03
  include/swift/ABI/CompactFunctionPointer.h
  include/swift/Basic/LangOptions.h
  include/swift/Runtime/Config.h
  lib/IRGen/IRGenSIL.cpp
  lib/SILGen/SILGenApply.cpp
  lib/SILGen/SILGenExpr.cpp
  lib/SILGen/SILGenFunction.h
  stdlib/cmake/modules/SwiftSource.cmake
  stdlib/public/core/KeyPath.swift
  stdlib/public/runtime/Exclusivity.cpp
  test/DebugInfo/move_function_dbginfo.swift
  test/DebugInfo/move_function_dbginfo_async.swift
  test/SILGen/keypaths_objc.swift
  validation-test/compiler_crashers_2_fixed/sr16076.swift
Labels: :arrow_heading_down: Upstream Tracking

#4471 ci: launch ci runner instance on demands
  .github/workflows/build-toolchain.yml
Labels: check-self-hosted-ci

#4485 Use Yams 5.0.1 to fix Ubuntu 18.04 build
  utils/update_checkout/update-checkout-config.json
Labels: release
