Repository swiftwasm/swift, pull requests merged in 2022-05, with the labels that each got.

#4545 Build SwiftWasm distribution archive for Ubuntu 22.04
  .github/workflows/build-toolchain.yml
  utils/webassembly/build-toolchain.sh
  utils/webassembly/linux/install-dependencies.sh
Labels: continuous integration

#4550 5.7: Build SwiftWasm distribution archive for Ubuntu 22.04
  .github/workflows/build-toolchain.yml
  utils/webassembly/build-toolchain.sh
  utils/webassembly/linux/install-dependencies.sh
Labels: continuous integration, release

#4579 Merge main 2022-05-20
  include/swift/AST/DiagnosticsClangImporter.def
  include/swift/AST/DiagnosticsSema.def
  include/swift/AST/SearchPathOptions.h
  include/swift/Basic/Version.h
  include/swift/Reflection/TypeRefBuilder.h
  include/swift/Sema/CSFix.h
  include/swift/Serialization/Validation.h
  lib/APIDigester/ModuleAnalyzerNodes.cpp
  lib/ASTSectionImporter/ASTSectionImporter.cpp
  lib/Basic/Version.cpp
  lib/ClangImporter/ClangImporter.cpp
  lib/Frontend/CompilerInvocation.cpp
  lib/Frontend/ModuleInterfaceLoader.cpp
  lib/Sema/CSClosure.cpp
  lib/Sema/CSDiagnostics.h
  lib/Sema/CSFix.cpp
  lib/Sema/CSStep.cpp
  lib/Sema/CSStep.h
  lib/Sema/TypeCheckAvailability.cpp
  lib/Serialization/ModuleFile.cpp
  lib/Serialization/ModuleFileSharedCore.cpp
  lib/Serialization/ModuleFileSharedCore.h
  lib/Serialization/ModuleFormat.h
  lib/Serialization/SerializedModuleLoader.cpp
  stdlib/public/SwiftShims/RuntimeShims.h
  stdlib/public/core/Assert.swift
  stdlib/public/core/Availability.swift
  stdlib/public/core/StringCharacterView.swift
  stdlib/public/core/StringGuts.swift
  stdlib/public/core/StringIndexConversions.swift
  stdlib/public/core/StringIndexValidation.swift
  stdlib/public/core/StringUTF16View.swift
  stdlib/public/core/StringUTF8View.swift
  stdlib/public/core/StringUnicodeScalarView.swift
  stdlib/public/runtime/Bincompat.cpp
  stdlib/public/runtime/EnvironmentVariables.cpp
  stdlib/public/runtime/EnvironmentVariables.def
  test/Constraints/closures.swift
  test/Constraints/generics.swift
  test/Distributed/Runtime/distributed_actor_init_local.swift
  test/Interop/Cxx/stdlib/libstdcxx-module-interface.swift
  test/Interop/Cxx/stdlib/use-std-string.swift
  test/Reflection/Inputs/Conformances.swift
  test/Reflection/conformance_descriptors.swift
  test/Serialization/restrict-swiftmodule-to-sdk.swift
  test/attr/attr_inlinable_available.swift
  test/expr/closure/multi_statement.swift
  test/expr/unary/keypath/keypath.swift
  test/lit.cfg
  test/stdlib/StringIndex.swift
  test/stdlib/StringIndex_bincompat.swift
  test/stdlib/StringTraps.swift
  tools/SourceKit/lib/SwiftLang/SwiftASTManager.cpp
  tools/lldb-moduleimport-test/lldb-moduleimport-test.cpp
  unittests/FrontendTool/ModuleLoadingTests.cpp
  utils/availability-macros.def
  utils/webassembly/wasm-run.py
Labels: :arrow_heading_down: Upstream Tracking

#4605 Merge main 2022-05-29
  include/swift/Runtime/RuntimeFnWrappersGen.h
  lib/IRGen/GenCall.cpp
  lib/IRGen/IRGenModule.cpp
  lib/IRGen/IRGenModule.h
  lib/IRGen/IRGenSIL.cpp
  test/ModuleInterface/SilencePreconcurrency.swiftinterface
Labels: :arrow_heading_down: Upstream Tracking
